### PR TITLE
adds support for filebeat on windows

### PR DESCRIPTION
**Pull request by coffeepac**
Its a bit hacked in but I've got it running in production.  I'm open to any comments/suggestions for changes.

### CODE REVIEW

**Comment by vkhatri** [comment]
@coffeepac Thank you for the PR! I am not working on Windows at the moment, but LGTM.

Looks like CI is failing. Also, it is not a good idea to update cookbook version in PR. Could you please re base the PR accordingly?

**Comment by coffeepac** [comment]
@vkhatri I will patch this up tomorrow to fix ci and bump the version. Thought I had!   Will bump a minor revisions. Feel free to ping me for future windows stuff.

**Comment by coffeepac** [comment]
@vkhatri I'll back out the version change (sorry, missed the not) but why is it a bad idea?

**Comment by vkhatri** [comment]
@coffeepac It is just version control differs from project to project and as a best practice it is better left off to the maintainers.

Sorry to say this, but you will have to rebase the PR or submit another one. `package_url` is now set to `auto` to minimize the derived attributes in the cookbook. 

I will wait for the new PR, before releasing new version.

**Comment by coffeepac** [comment]
@vkhatri this will pass in about 10 minutes (I forgot to add a line to the CHANGELOG) but its rebased and ready to go.

**Pull request merged**
