### PR TITLE
Add restart recipe

### PR DESCRIPTION
**Pull request by sevaorlov**
This one is for https://github.com/vkhatri/chef-filebeat/issues/34
What do you think?

### CODE REVIEW

**Comment by dissonanz** [comment]
Hey @vsorlov, how about sending a notification to the filebeat service from the package resource instead?

```
# filebeat::install_package
package 'filebeat' do
  version node['platform_family'] == 'rhel' ? node['filebeat']['version'] + '-1' : node['filebeat']['version']
  notifies :restart, 'service[filebeat]'
end
```

**Comment by sevaorlov** [comment]
@dissonanz, do you think a separate recipe for restarting filebeat will not be ever needed?

**Comment by dissonanz** [comment]
As long as we have `service[filebeat]` defined, we can always use a notification to trigger a restart either `:immediately` or `:delayed`. I don't see any reason to create a separate recipe for this. Even if we did, the recipe would need to either be run separately or have a different name to avoid namespace collision with the existing service resource.

**Comment by sevaorlov** [comment]
@dissonanz, I mean what if we encounter some problems with filebeat and want to restart it? is there a way to restart filebeat without sshing to each instance?

**Comment by dissonanz** [comment]
@vsorlov that sounds like a task for your monitoring and remediation system, not for the configuration management system. How would you detect that there is a problem with filebeat?

If you did try to perform the restart using Chef, how would you accomplish it? If you added a restart recipe to the run list, and you're running Chef on a schedule, you would restart filebeat every chef run until the recipe is removed from the run list. On the other hand, if you use knife ssh  to perform the restart, it's simpler to use execute a `service filebeat restart` using knife ssh.

**Comment by sevaorlov** [comment]
@dissonanz, I detected it when I regenerated filebeat config and found out that logs in logstash didn't correspond to it. I tried to restart filebeat and it worked. After it I added filebeat restart recipe and executed it on my instances.
Didn't know about knife ssh, will look into it, thanks.

**Comment by sevaorlov** [comment]
@dissonanz, I updated request, not sure what I need to do with windows installation. And do I need to add something in changelog?

**Comment by dissonanz** [comment]
@vsorlov filebeat is installed as a service on Windows, so this should work for windows too. As for the changelog, maybe that's why @vkhatri hasn't released my PR yet. I recommend adding to the changelog.

**Comment by vkhatri** [comment]
@vsorlov @dissonanz Sorry for the delay and any inconvenience caused.

Thank you for the PR!

**Pull request merged**
